# Generated by Django 5.0.5 on 2024-05-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_ambiente', '0007_remove_ambiente_ubicacion_ambiente'),
        ('modulo_curso', '0010_alter_curso_options_remove_curso_fkescuela_and_more'),
        ('modulo_docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cic_año', models.CharField(max_length=4)),
                ('cic_semestre', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Ciclo académico',
            },
        ),
        migrations.CreateModel(
            name='dia_semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_nombre', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Día de la semana',
            },
        ),
        migrations.CreateModel(
            name='grupo_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=1)),
                ('fk_ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.ciclo_academico')),
                ('fk_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.curso')),
                ('fk_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.docente')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_de_inicio', models.CharField(default='00:00', max_length=5, verbose_name='Hora de inicio')),
                ('hora_final', models.CharField(default='00:00', max_length=5)),
                ('motivo_cambio', models.CharField(blank=True, max_length=150, null=True)),
                ('ambiente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.ambiente')),
                ('día', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.dia_semana', verbose_name='Día')),
                ('fk_grupo_horario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.grupo_horario', verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
