# Generated by Django 5.0.6 on 2024-06-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0009_delete_horarioescuela'),
        ('modulo_curso', '0011_curso_ciclo_curso'),
        ('modulo_horario', '0004_horario_fk_grupo_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='escuela_ambiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FK_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.ambiente', verbose_name='Ambiente')),
                ('FK_ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.ciclo_academico', verbose_name='ciclo')),
                ('FK_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.escuela', verbose_name='Escuela')),
            ],
        ),
    ]
