# Generated by Django 5.0.6 on 2024-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_horario', '0005_escuela_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_horario',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
