# Generated by Django 5.0.4 on 2024-04-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amb_nombre', models.CharField(max_length=30)),
                ('amb_capacidad', models.SmallIntegerField()),
                ('amb_estado', models.BinaryField()),
                ('amb_ubicacion', models.IntegerField(default=1)),
                ('amb_tipo', models.IntegerField(default=1)),
                ('FKedificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.edificio')),
                ('FKtipoambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.tipo_ambiente')),
            ],
        ),
    ]
