# Generated by Django 5.0.4 on 2024-04-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0002_ambiente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='FKtipoambiente',
            new_name='FKtipo_ambiente',
        ),
        migrations.RenameField(
            model_name='ambiente',
            old_name='amb_capacidad',
            new_name='capacidad_ambiente',
        ),
        migrations.RenameField(
            model_name='ambiente',
            old_name='amb_nombre',
            new_name='nombre_ambiente',
        ),
        migrations.RenameField(
            model_name='ambiente',
            old_name='amb_ubicacion',
            new_name='ubicacion_ambiente',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='amb_estado',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='amb_tipo',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='estado_ambiente',
            field=models.IntegerField(default=1),
        ),
    ]
