# Generated by Django 5.0.4 on 2024-04-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0004_rename_edi_nombre_edificio_nombre_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='FKedificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.edificio', verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='FKtipo_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.tipo_ambiente', verbose_name='Tipo de Ambiente'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='capacidad_ambiente',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='estado_ambiente',
            field=models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupado'), ('M', 'Mantenimiento')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ubicacion_ambiente',
            field=models.TextField(max_length=100),
        ),
    ]
