# Generated by Django 5.0.4 on 2024-04-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0005_alter_ambiente_fkedificio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambiente',
            options={'verbose_name_plural': 'Ambiente'},
        ),
        migrations.AlterModelOptions(
            name='edificio',
            options={'verbose_name_plural': 'Edificio'},
        ),
        migrations.AlterModelOptions(
            name='tipo_ambiente',
            options={'verbose_name_plural': 'Tipo de ambiente'},
        ),
    ]
