# Generated by Django 5.0.5 on 2024-05-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0006_alter_ambiente_options_alter_edificio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='ubicacion_ambiente',
        ),
    ]
