# Generated by Django 5.0.6 on 2024-06-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0007_remove_ambiente_ubicacion_ambiente'),
        ('modulo_curso', '0011_curso_ciclo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='piso',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.CreateModel(
            name='horarioEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('FKambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ambiente.ambiente', verbose_name='Ambiente')),
                ('FKescuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.escuela', verbose_name='Escuela')),
            ],
        ),
    ]
