# Generated by Django 5.0.6 on 2024-06-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0008_ambiente_piso_horarioescuela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='horarioEscuela',
        ),
    ]
