# Generated by Django 5.0.6 on 2024-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ambiente', '0009_delete_horarioescuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='piso',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
