# Generated by Django 5.0.4 on 2024-04-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcur_descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esc_nombre', models.CharField(max_length=60)),
                ('esc_facultad', models.IntegerField(default=1)),
                ('fk_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.facultad')),
            ],
        ),
    ]
