# Generated by Django 5.0.4 on 2024-04-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0002_curso_plan_estudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='cur_nombre',
            new_name='nombre_curso',
        ),
        migrations.RenameField(
            model_name='escuela',
            old_name='esc_nombre',
            new_name='nombre_escuela',
        ),
        migrations.RenameField(
            model_name='facultad',
            old_name='fac_nombre',
            new_name='nombre_facultad',
        ),
        migrations.RenameField(
            model_name='tipo_curso',
            old_name='tcur_descripcion',
            new_name='descripcion_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_escuela',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_horaspracticas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_horassemana',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_horasteoricas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_horastotales',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_plan',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='cur_tipo',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='esc_facultad',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='fk_escuela',
        ),
        migrations.RemoveField(
            model_name='plan_estudio',
            name='FKcurso',
        ),
        migrations.AddField(
            model_name='curso',
            name='FKplan_estudio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.plan_estudio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_practicas',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_semana',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_teoricas',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_totales',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='escuela',
            name='director_escuela',
            field=models.CharField(default='Sin director', max_length=60),
        ),
        migrations.AddField(
            model_name='escuela',
            name='fk_facultad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.facultad'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='responsable_facultad',
            field=models.CharField(default='Sin responsable', max_length=100),
        ),
        migrations.AddField(
            model_name='plan_estudio',
            name='fk_escuela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.escuela'),
        ),
        migrations.AddField(
            model_name='tipo_curso',
            name='tipo_curso',
            field=models.CharField(default='Curso presencial', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan_estudio',
            name='plan_nombre',
            field=models.CharField(default='plan 2024', max_length=60),
        ),
    ]
