# Generated by Django 5.0.4 on 2024-04-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0003_rename_cur_nombre_curso_nombre_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_estudio',
            name='plan_curso',
        ),
    ]
