# Generated by Django 5.0.4 on 2024-04-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0004_remove_plan_estudio_plan_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='horas_semana',
        ),
    ]
