# Generated by Django 5.0.4 on 2024-04-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0005_remove_curso_horas_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name_plural': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='escuela',
            options={'verbose_name_plural': 'Escuela'},
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'verbose_name_plural': 'Facultad'},
        ),
        migrations.AlterModelOptions(
            name='plan_estudio',
            options={'verbose_name_plural': 'Plan de estudio'},
        ),
        migrations.AlterModelOptions(
            name='tipo_curso',
            options={'verbose_name_plural': 'Tipo de curso'},
        ),
    ]
