# Generated by Django 5.0.4 on 2024-05-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0007_plan_estudio_plan_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.CreateModel(
            name='grupo_horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=1)),
                ('fk_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_curso.curso')),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
    ]
