# Generated by Django 5.0.4 on 2024-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0008_alter_curso_options_curso_codigo_curso_grupo_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
