# Generated by Django 5.0.5 on 2024-05-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0009_alter_curso_codigo_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name_plural': 'Curso'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='FKescuela',
        ),
        migrations.DeleteModel(
            name='grupo_horario',
        ),
    ]
