# Generated by Django 5.0.5 on 2024-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0010_alter_curso_options_remove_curso_fkescuela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo_curso',
            field=models.SmallIntegerField(default=1),
        ),
    ]
