# Generated by Django 5.0.6 on 2024-06-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_curso', '0011_curso_ciclo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='amb',
            field=models.SmallIntegerField(default=1),
        ),
    ]
