# Generated by Django 5.0.5 on 2024-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento_academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_nombre', models.CharField(max_length=50)),
                ('dep_director', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departamento académico',
            },
        ),
        migrations.CreateModel(
            name='disponibilidad_docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ddo_horainicio', models.TimeField()),
                ('ddo_horafin', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Disponibilidad docente',
                'ordering': ['FKdocente'],
            },
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_nombres', models.CharField(max_length=200)),
                ('doc_especialidad', models.CharField(max_length=100)),
                ('doc_email', models.CharField(max_length=50)),
                ('doc_estado', models.CharField(max_length=10)),
                ('doc_telefono', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='tipo_contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_nombre', models.CharField(max_length=50)),
                ('tp_descripcion', models.CharField(max_length=100)),
                ('tp_horas', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tipo de contrato',
            },
        ),
    ]
