# Generated by Django 5.0.6 on 2024-05-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_docente', '0002_initial'),
        ('modulo_horario', '0003_grupo_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='docente_grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FKdocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_docente.docente')),
                ('FKgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_horario.grupo_horario')),
            ],
            options={
                'verbose_name_plural': 'Docente grupo',
                'ordering': ['id'],
            },
        ),
    ]
